# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# Interactive operation...
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
#
# Default to human readable figures
alias df='df -h'
alias du='du -h'
#
# Misc :)
alias less='less -r'                          # raw control characters
alias whence='type -a'                        # where, of a sort
alias grep='grep --color'                     # show differences in colour
alias egrep='egrep --color=auto'              # show differences in colour
alias fgrep='fgrep --color=auto'              # show differences in colour
#
# Some shortcuts for different directory listings
alias ls='ls -hF --color=tty'                 # classify files in colour
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -l'                              # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'                              #

export LESSCHARSET=latin1
alias less='/bin/less -r'
alias cs='cscope'
alias ls='/bin/ls -F --color=tty --show-control-chars'

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias rm='rm -i'
alias vi='vim'
alias e='exit'
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi
## Tizen SDK configuration
# This is generated by Tizen SDK. Please do not modify by yourself.
# Set sbi, sdb environment path
export PATH=$PATH:/home/xiaoqiang/tizen_sdk/SDK/sdb:/home/xiaoqiang/tizen_sdk/SDK/build-system/bin
## End Tizen SDK configuration
function osc_m2()
{ 
#export socks_proxy=proxy.jf.intel.com:1080;
#  export http_proxy=http://proxy01.pd.intel.com:911; 
  tsocks  osc -A m2 $@; 
#unset http_proxy;
#  unset socks_proxy;
}

function osc_ti()
{ 
  tsocks osc -A tizen $@; 
}
function osc_tz()
{ 
  tsocks osc -A tz $@; 
}

function osc_suse()
{ 
  tsocks osc -A suse $@; 
}


function osc_sa()
{ 
#export socks_proxy=proxy.jf.intel.com:1080;
#export http_proxy=http://proxy01.pd.intel.com:911; 
  osc -A sa $@; 
#  unset http_proxy;
#  unset socks_proxy;
}
# http://download.tizen.org/snapshots/tizen_20120514.2/repos/base/armv7l/packages/
# http://download.tizen.org/snapshots/tizen_20120514.2/repos/main/armv7l/packages/
export GIT_AUTHOR_NAME="Zhang Qiang"
export GIT_AUTHOR_EMAIL="qiang.z.zhang@intel.com"
export REPO_BASE=http://otc-projects.bj.intel.com/Tizen/repo_mirror/tizen_20120509.5/repos/base/ia32/packages/
export REPO_MAIN=http://otc-projects.bj.intel.com/Tizen/repo_mirror/tizen_20120509.5/repos/main/ia32/packages/
export REPO_BASE=http://otc-projects.bj.intel.com/Tizen/repo_mirror/tizen_20120509.5/repos/base/armv7l/packages/
export REPO_MAIN=http://otc-projects.bj.intel.com/Tizen/repo_mirror/tizen_20120509.5/repos/main/armv7l/packages/
export REPO_BASE=http://download.tz.otcshare.org/snapshots/tizen_20120507.8/repos/tzbase/ia32/packages/
export REPO_MAIN=http://download.tz.otcshare.org/snapshots/tizen_20120507.8/repos/tzmain/ia32/packages/
export TIZEN_BUILD_ROOT=/home/xiaoqiang/GBS-ROOT/
export VIRTUAL_ENV=/

wo() {
    dir="$HOME/otctools"
    subdir="$dir/$1"
    if [ -d "$subdir" ]; then
        cd $subdir
    else
        cd $dir
    fi
}
_wo() 
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    dir="$HOME/otctools"
    if [ "$cur" == "" ]; then
        opts=$(find $dir -maxdepth 1 -mindepth 1 -type d -exec basename \{} \;)
    else
        opts=$(find $dir -maxdepth 1 -mindepth 1 -type d -name "$cur*" -exec basename \{} \;)
    fi

    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}
complete -F _wo wo

#. ~/.gbs.bash

export http_proxy=http://proxy01.cd.intel.com:911/
export https_proxy=http://proxy01.cd.intel.com:911/
export no_proxy=.intel.com,10.238.158.218
#export no_proxy=*.intel.com
export PATH=~/bin/:$PATH
set -o vi
export EDITOR=vim
export ITEST_ENV_PATH=/home/xiaoqiang/otctools/itest/GBS
export ITEST_SUDO_PASSWD=850122
export BUILD_DIR=/usr/lib/build/
. ~/otctools/gbs/data/gbs.sh
